# Generated by Django 4.2.6 on 2023-11-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VIPCustomer',
        ),
    ]
