# Generated by Django 4.2.6 on 2023-11-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_rename_product_orderitem_ordered_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ordered_product',
            new_name='product',
        ),
    ]
